export const DUMMY_QA = [
    {
        prompt: "Addition",
        question: '9 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "A",
      },
      {
        prompt: "Addition",
        question: '9999 + 1?',
        optionA: "10",
        optionB: "10000",
        optionC: "8",
        optionD: "6",
        answer: "B",
      },
      {
        prompt: "Addition",
        question: '10 + 1?',
        optionA: "11",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "A",
      },
      {
        prompt: "Addition",
        question: '7 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "C",
      },
      {
        prompt: "Addition",
        question: '5 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "D",
      },
      {
        prompt: "Addition",
        question: '11 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "12",
        answer: "D",
      },
      {
        prompt: "Addition",
        question: '21 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "22",
        answer: "D",
      },
      {
        prompt: "Addition",
        question: '15 + 1?',
        optionA: "10",
        optionB: "100000",
        optionC: "8",
        optionD: "16",
        answer: "D",
      },
      {
        prompt: "Addition",
        question: '100 + 1?',
        optionA: "101",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "A",
      },
      {
        prompt: "Addition",
        question: '19 + 1?',
        optionA: "20",
        optionB: "100000",
        optionC: "8",
        optionD: "6",
        answer: "A",
      },
]